# Generated by Django 6.0.7 on 2026-07-18 18:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('author_name', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('bulleted_list', 3), ('quote', 6), ('code', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'max_length': 120, 'template': 'blog/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blog/blocks/paragraph.html'}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 240}), 3: ('wagtail.blocks.ListBlock', (2,), {'template': 'blog/blocks/bulleted_list.html'}), 4: ('wagtail.blocks.TextBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('language', 7), ('code', 4)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
